### PR TITLE
Do not allow static directory listings

### LINKED ISSUE #156: Static directory indexes are visible
If you go to a folder, e.g. https://shuttles.rpi.edu/static/, users see a directory index. This is wrong.

### PR DESCRIPTION
**Pull request by kochman**
Create a custom filesystem type that returns `os.ErrNotExist` for any directories. This prevents `http.FileServer` from returning static directory listings (e.g. https://shuttles.rpi.edu/static/ will now return 404).

Resolves #156.

### CODE REVIEW

File: api/filesystem.go [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+	s, err := f.Stat()
+	if err != nil {
+		return nil, err
+	}
+	if s.IsDir() {
+		return nil, os.ErrNotExist
+	}
+
+	return f, nil
```
Comment (garoller) [inline api/filesystem.go]: The current version of the shuttle tracker returns a 404 when going to https://shuttles.rpi.edu/static/app.js or other files in static (`admin.html` and `favicon.ico`). 

With these changes the files are returned and visible to the user, why is this better than returning a 404? Also, when someone goes to https://shuttles.rpi.edu/static/app.js the content type of the response is javascript.

Comment (kochman) [reply api/filesystem.go]: Which URLs specifically are returning files? I'm trying to reproduce what you described but I'm only getting 404s as expected.

Comment (garoller) [reply api/filesystem.go]: http://localhost:8080/static/admin.html takes me to the admin page.
http://localhost:8080/static/app.js and http://localhost:8080/static/favicon.ico display files.
http://localhost:8080/static/index.html redirects to http://localhost:8080/static/, which returns a 404.

Here's a screenshot of what I'm seeing for http://localhost:8080/static/app.js.
appjs


I edited the links in the above comment to be more clear, sorry about that.
