### PR TITLE
Route Scheduling Fix

### LINKED ISSUE #133: Route Scheduling Does Not Work

### PR DESCRIPTION
**Pull request by jlyon1**
This should fix #133

### CODE REVIEW

**Comment by kochman** [comment]
@jlyon1 Can we get the coverage in the `model.Time` comparisons up a little? There are some branches that don't have tests: https://codecov.io/gh/wtg/shuttletracker/src/e9296f876eeba67c1585f60939cef210bdf82184/model/time.go

File: api/routes.go [hunk 1]
```diff
@@ -2,60 +2,48 @@ package api
...
 	log "github.com/Sirupsen/logrus"
 	"github.com/gorilla/mux"
-
 	"github.com/wtg/shuttletracker/model"
+	"gopkg.in/cas.v1"
 )
 
 //RouteIsActive determines if the current time means a route should be active or not
 //TODO: Move this to updater
 func (api *API) RouteIsActive(r *model.Route) bool {
```
Comment (kochman) [inline api/routes.go]: I'm not sure about this method. Why does it need to modify the route in the database? Can the API just determine if each route is active after it pulls them from the database?

I think we shouldn't try to store/persist data (whether a route is active) if it can be reasonably calculated from other data (route activation times). Gives us one source of truth, is easier to reason about, and prevents some weird issues related to caching and locking.

Additionally, this method appears to do two things: modify route activation status for the API, and return a boolean for testing. It should just do one thing, and the tests can verify that the result is as expected through another manner.

File: api/routes.go [hunk 2]
```diff
@@ -2,60 +2,48 @@ package api
...
 			state = val.State
 			break
-
 		}
 	}
 
 	route := model.Route{}
-	if(api.db != nil){
+	//Check if db is nil for testing
+	if api.db != nil {
```
Comment (kochman) [inline api/routes.go]: We should construct an instance of `API` with a mock database. The code shouldn't be branching differently to handle being tested.

File: api/routes.go [hunk 3]
```diff
@@ -138,24 +127,12 @@ func (api *API) RoutesCreateHandler(w http.ResponseWriter, r *http.Request) {
 
 	// Here do the interpolation
 	// now we get the Segment for each segment ( this should be stored in database, just store it inside route for god sake)
-	fmt.Printf("Size of coordinates = %d", len(coords))
+	// fmt.Printf("Size of coordinates = %d", len(coords))
```
Comment (kochman) [inline api/routes.go]: can just delete

File: api/routes.go [hunk 4]
```diff
@@ -183,7 +160,7 @@ func (api *API) RoutesDeleteHandler(w http.ResponseWriter, r *http.Request) {
 		return
 	}
 	vars := mux.Vars(r)
-	fmt.Printf(vars["id"])
+	// fmt.Printf(vars["id"])
```
Comment (kochman) [inline api/routes.go]: also delete

File: api/routes.go [hunk 5]
```diff
@@ -299,7 +274,7 @@ func (api *API) StopsDeleteHandler(w http.ResponseWriter, r *http.Request) {
 
 	vars := mux.Vars(r)
 	log.Debugf("deleting", vars["id"])
-	fmt.Printf(vars["id"])
+	// fmt.Printf(vars["id"])
```
Comment (kochman) [inline api/routes.go]: delete

File: api/routes_test.go [hunk 6]
```diff
@@ -0,0 +1,115 @@
...
+		State: 0,
+	}
+	t2 = model.Time{
+		Day:   time.Now().Weekday(),
+		Time:  time.Now().Add(5 * time.Minute),
+		State: 1,
+	}
+	interval = append(interval, t1, t2)
+	TestRoute.TimeInterval = interval
+	if api.RouteIsActive(&TestRoute) {
```
Comment (kochman) [inline api/routes_test.go]: See comment on `RouteIsActive`

**Comment by kochman** [comment]
More thoughts about how to fix `RouteIsActive`...

An option I like after thinking about it for two minutes is creating an `IsActive()` method on `model.Route` that will calculate if the route should be marked as active. Then we can implement the Marshaler interface to return the active status through the API (see https://github.com/wtg/elecnoms/blob/278019df4bb0a22c95d246e964f5caffece8b3ca/cms.go#L49)

**Comment by kochman** [comment]
Thinking about it more... `Active` could just be a field that is populated by the database implementation whenever a route is retrieved. The database implementation would be responsible for determining when a route is active internally.

I’m not sure if this is better or worse than making it a method on a route. We should talk more.

**Comment by jlyon1** [comment]
Made some of those changes, what do you think Coach @kochman ?

**Comment by jlyon1** [comment]
Looks Like something got messed up in the merge, I'll fix it in a bit.

**Comment by kochman** [comment]
@jlyon1 did you figure out why the tests sometimes fail?

File: api/routes.go [hunk 7]
```diff
@@ -180,18 +110,20 @@ func (api *API) RoutesDeleteHandler(w http.ResponseWriter, r *http.Request) {
...
 	if err != nil {
 		http.Error(w, err.Error(), http.StatusInternalServerError)
 	}
 }
 
 type sched struct {
-	Times []model.WeekTime `json:times`
-	ID    string           `json:id`
+	Times []model.Time `json:times`
+	ID    string       `json:id`
```
Comment (kochman) [inline api/routes.go]: These struct tags need quotation marks around the names https://travis-ci.org/wtg/shuttletracker/jobs/357929397#L549

File: model/time.go [hunk 8]
```diff
@@ -0,0 +1,69 @@
...
+import (
+	"fmt"
+	"time"
+)
+
+// Time struct is used to store route enable/disable times, so we can compare times without a date
+type Time struct {
+	Time  time.Time    `json:time`
+	Day   time.Weekday `json:day`
+	State int          `json:on`
```
Comment (kochman) [inline model/time.go]: these struct tags need quotation marks around names

File: database/database.go [hunk 9]
```diff
@@ -7,6 +7,36 @@ import (
 	"github.com/wtg/shuttletracker/model"
 )
 
+//RouteIsActive determines if a given route is active based on its schedule intervals
+func RouteIsActive(r *model.Route) {
```
Comment (kochman) [inline database/database.go]: Can we rename this? Maybe `SetRouteActivationStatus` or something to indicate that it modifies the route instead of returning something.
